package cr.ac.una.reservas.presentation.controller;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import cr.ac.una.reservas.logic.ServiceModel;
import cr.ac.una.reservas.presentation.view.VistaUtil;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Insets;

@SuppressWarnings({"unused", "WeakerAccess", "FieldCanBeLocal"})
public class CambiarClaveController extends JDialog {
    public JPanel contentPane;
    public JLabel lblActual;
    public JLabel lblNueva2;
    public JPasswordField txtClaveActual;
    public JPasswordField txtClaveNueva2;
    public JButton btnGuardar;
    public JPasswordField txtClaveNueva1;
    public JButton btnCancelar;
    public JLabel lblNueva1;
    private String userId;

    public CambiarClaveController(JFrame owner, String userId) {
        super(owner, "Cambiar clave", true);
        this.userId = userId;
        $$$setupUI$$$();
        setContentPane(contentPane);
        setSize(420, 200);
        setLocationRelativeTo(owner);
        btnCancelar.addActionListener(e -> dispose());
        btnGuardar.addActionListener(e -> guardar());
    }

    private void guardar() {
        String actual = new String(txtClaveActual.getPassword());
        String nueva = new String(txtClaveNueva1.getPassword());
        String confirmacion = new String(txtClaveNueva2.getPassword());
        if (actual.isBlank() || nueva.isBlank() || confirmacion.isBlank()) {
            VistaUtil.error(this, "Debe completar todos los campos.");
            return;
        }
        if (!nueva.equals(confirmacion)) {
            VistaUtil.error(this, "Las nuevas claves no coinciden.");
            return;
        }
        if (ServiceModel.getInstance().cambiarClave(userId, actual, nueva)) {
            VistaUtil.mensaje(this, "Clave actualizada.");
            dispose();
        } else {
            VistaUtil.error(this, "No se pudo cambiar la clave. Verifique la clave actual.");
        }
    }

    private void createUIComponents() {
        ImageIcon enterOriginal = new ImageIcon(getClass().getResource("/images/check.png"));
        Image enterScaled = enterOriginal.getImage().getScaledInstance(24, 24, Image.SCALE_SMOOTH);
        btnGuardar = new JButton("Guardar", new ImageIcon(enterScaled));

        ImageIcon enterOriginal2 = new ImageIcon(getClass().getResource("/images/cancelar.png"));
        Image enterScaled2 = enterOriginal2.getImage().getScaledInstance(24, 24, Image.SCALE_SMOOTH);
        btnCancelar = new JButton("Cancelar", new ImageIcon(enterScaled2));
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(4, 3, new Insets(15, 15, 15, 15), -1, -1));
        lblActual = new JLabel();
        lblActual.setText("Clave Actual:");
        contentPane.add(lblActual, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtClaveActual = new JPasswordField();
        contentPane.add(txtClaveActual, new GridConstraints(0, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblNueva2 = new JLabel();
        lblNueva2.setText("Clave Nueva:");
        contentPane.add(lblNueva2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtClaveNueva2 = new JPasswordField();
        contentPane.add(txtClaveNueva2, new GridConstraints(2, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnGuardar.setText("Guardar");
        contentPane.add(btnGuardar, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtClaveNueva1 = new JPasswordField();
        contentPane.add(txtClaveNueva1, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lblNueva1 = new JLabel();
        lblNueva1.setText("Clave Nueva:");
        contentPane.add(lblNueva1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnCancelar.setText("Cancelar");
        contentPane.add(btnCancelar, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
