package cr.ac.una.reservas.presentation.controller;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import cr.ac.una.reservas.logic.ServiceModel;
import cr.ac.una.reservas.logic.Usuario;
import cr.ac.una.reservas.presentation.view.VistaUtil;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Insets;

@SuppressWarnings({"unused", "WeakerAccess", "FieldCanBeLocal"})
public class LoginController extends JFrame {
    public JPanel contentPane;
    public JLabel lblId;
    public JLabel lblClave;
    public JTextField txtId;
    public JPasswordField txtClave;
    public JButton btnIngresar;
    public JPanel loginPanel;
    public JLabel lbLogo;
    public JButton btnCancelar;
    public JButton btnCambiarClave;
    private ServiceModel service;

    public LoginController() {
        $$$setupUI$$$();
        service = ServiceModel.getInstance();
        setContentPane(contentPane);
        setTitle("Ingreso al sistema");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(360, 280);
        setLocationRelativeTo(null);
        btnIngresar.addActionListener(e -> intentarLogin());
        btnCancelar.addActionListener(e -> dispose());
        btnCambiarClave.addActionListener(e -> abrirCambiarClave());
    }

    private void intentarLogin() {
        try {
            String id = txtId.getText().trim();
            String clave = new String(txtClave.getPassword());
            if (id.isBlank() || clave.isBlank()) {
                VistaUtil.error(this, "Debe indicar id y clave.");
                return;
            }
            Usuario usuario = service.login(id, clave);
            if (usuario == null) {
                VistaUtil.error(this, "Credenciales incorrectas.");
                return;
            }
            dispose();
            new MainController(usuario).setVisible(true);
        } catch (Exception ex) {
            VistaUtil.error(this, "Error al ingresar: " + ex.getMessage());
        }
    }

    private void abrirCambiarClave() {
        String id = txtId.getText().trim();
        if (id.isBlank()) {
            VistaUtil.error(this, "Debe indicar su ID para cambiar la clave.");
            return;
        }
        new CambiarClaveController(this, id).setVisible(true);
    }

    private void createUIComponents() {
        ImageIcon original = new ImageIcon(getClass().getResource("/images/login.png"));
        Image scaledImage = original.getImage().getScaledInstance(55, 55, Image.SCALE_SMOOTH);
        lbLogo = new JLabel(new ImageIcon(scaledImage));

        ImageIcon enterOriginal = new ImageIcon(getClass().getResource("/images/login-enter.png"));
        Image enterScaled = enterOriginal.getImage().getScaledInstance(24, 24, Image.SCALE_SMOOTH);
        btnIngresar = new JButton("Ingresar", new ImageIcon(enterScaled));

        ImageIcon enterOriginal2 = new ImageIcon(getClass().getResource("/images/cancelar.png"));
        Image enterScaled2 = enterOriginal2.getImage().getScaledInstance(24, 24, Image.SCALE_SMOOTH);
        btnCancelar = new JButton("Cancelar", new ImageIcon(enterScaled2));

        ImageIcon enterOriginal3 = new ImageIcon(getClass().getResource("/images/cambiar-imagen.png"));
        Image enterScaled3 = enterOriginal3.getImage().getScaledInstance(24, 24, Image.SCALE_SMOOTH);
        btnCambiarClave = new JButton("Cambiar", new ImageIcon(enterScaled3));
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(1, 1, new Insets(15, 15, 15, 15), -1, -1));
        loginPanel = new JPanel();
        loginPanel.setLayout(new GridLayoutManager(4, 4, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(loginPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(300, 220), null, 0, false));
        btnIngresar.setText("Ingresar");
        loginPanel.add(btnIngresar, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(109, 34), null, 0, false));
        lbLogo.setText("");
        loginPanel.add(lbLogo, new GridConstraints(0, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(55, 55), null, 0, false));
        txtId = new JTextField();
        loginPanel.add(txtId, new GridConstraints(1, 1, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(109, 34), null, 0, false));
        lblId = new JLabel();
        lblId.setText("ID");
        loginPanel.add(lblId, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(50, 27), null, 0, false));
        lblClave = new JLabel();
        lblClave.setText("Clave:");
        loginPanel.add(lblClave, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(50, 17), null, 0, false));
        txtClave = new JPasswordField();
        txtClave.setText("");
        loginPanel.add(txtClave, new GridConstraints(2, 1, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(109, 34), null, 0, false));
        btnCancelar.setText("Cancelar");
        loginPanel.add(btnCancelar, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(109, 34), null, 0, false));
        btnCambiarClave.setText("Cambiar");
        loginPanel.add(btnCambiarClave, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(109, 34), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
