package cr.ac.una.reservas.presentation.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import cr.ac.una.reservas.logic.Categoria;
import cr.ac.una.reservas.logic.Recurso;
import cr.ac.una.reservas.logic.ServiceModel;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.time.LocalDate;
import java.util.List;

public class CalendarizacionView extends JPanel {
    private JPanel rootPanel;
    private JPanel panelNorte;
    private JTextField txtFecha;
    private JComboBox<Categoria> cmbCategoria;
    private JTable tabla;
    private DefaultTableModel modelo;
    private JButton btnCargar;
    private JButton btnPdf;

    public CalendarizacionView() {
        $$$setupUI$$$();
        if (rootPanel != this) {
            add(rootPanel);
        }
        cargarCategorias();
    }

    private void createUIComponents() {
        modelo = new DefaultTableModel();
        tabla = new JTable(modelo);
    }

    public void cargarCategorias() {
        cmbCategoria.removeAllItems();
        for (Categoria c : ServiceModel.getInstance().buscarCategorias("")) {
            cmbCategoria.addItem(c);
        }
    }

    public LocalDate getFechaSeleccionada() {
        return LocalDate.parse(txtFecha.getText().trim());
    }

    public String getCategoriaSeleccionada() {
        Categoria c = (Categoria) cmbCategoria.getSelectedItem();
        return c == null ? "" : c.getId();
    }

    public void mostrarMatrizHorarios(Object[][] matriz) {
        List<Recurso> recursos = ServiceModel.getInstance().recursosDeCategoria(getCategoriaSeleccionada());
        String[] cols = new String[recursos.size() + 1];
        cols[0] = "Hora";
        for (int i = 0; i < recursos.size(); i++) {
            cols[i + 1] = recursos.get(i).getDescripcion();
        }
        modelo.setColumnIdentifiers(cols);
        modelo.setRowCount(0);
        if (matriz != null) {
            for (Object[] fila : matriz) {
                modelo.addRow(fila);
            }
        }
    }

    public JTable getTabla() {
        return tabla;
    }

    public DefaultTableModel getModelo() {
        return modelo;
    }

    public JButton getBtnCargar() {
        return btnCargar;
    }

    public JButton getBtnPdf() {
        return btnPdf;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(2, 1, new Insets(8, 8, 8, 8), -1, -1));
        panelNorte = new JPanel();
        panelNorte.setLayout(new GridLayoutManager(1, 6, new Insets(0, 0, 0, 0), -1, -1));
        rootPanel.add(panelNorte, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Fecha (yyyy-MM-dd):");
        panelNorte.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtFecha = new JTextField();
        panelNorte.add(txtFecha, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(120, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Categoria:");
        panelNorte.add(label2, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cmbCategoria = new JComboBox();
        panelNorte.add(cmbCategoria, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnCargar = new JButton();
        btnCargar.setText("Mostrar");
        panelNorte.add(btnCargar, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnPdf = new JButton();
        btnPdf.setText("PDF");
        panelNorte.add(btnPdf, new GridConstraints(0, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        rootPanel.add(scrollPane1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPane1.setViewportView(tabla);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
