package cr.ac.una.reservas.presentation.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class CambiarClaveDialog extends JDialog {
    private JPanel contentPane;
    private JLabel lblActual;
    private JLabel lblNueva2;
    private JPasswordField txtClaveActual;
    private JPasswordField txtClaveNueva2;
    private JButton btnGuardar;
    private JPasswordField txtClaveNueva1;
    private JButton btnCancelar;
    private JLabel lblNueva1;

    public CambiarClaveDialog(JFrame owner) {
        super(owner, "Cambiar clave", true);
        $$$setupUI$$$();
        setContentPane(contentPane);
        setSize(420, 200);
        setLocationRelativeTo(owner);
    }

    public String getTxtClaveActual() {
        return new String(txtClaveActual.getPassword());
    }

    public String getTxtClaveNueva() {
        return new String(txtClaveNueva1.getPassword());
    }

    public String getTxtClaveNuevaConfirmacion() {
        return new String(txtClaveNueva2.getPassword());
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(4, 3, new Insets(15, 15, 15, 15), -1, -1));
        lblActual = new JLabel();
        lblActual.setText("Clave Actual:");
        contentPane.add(lblActual, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtClaveActual = new JPasswordField();
        contentPane.add(txtClaveActual, new GridConstraints(0, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblNueva2 = new JLabel();
        lblNueva2.setText("Clave Nueva:");
        contentPane.add(lblNueva2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtClaveNueva2 = new JPasswordField();
        contentPane.add(txtClaveNueva2, new GridConstraints(2, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnGuardar.setText("Guardar");
        contentPane.add(btnGuardar, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtClaveNueva1 = new JPasswordField();
        contentPane.add(txtClaveNueva1, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lblNueva1 = new JLabel();
        lblNueva1.setText("Clave Nueva:");
        contentPane.add(lblNueva1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnCancelar.setText("Cancelar");
        contentPane.add(btnCancelar, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    private void createUIComponents() {
        ImageIcon enterOriginal = new ImageIcon(getClass().getResource("/images/check.png"));
        Image enterScaled = enterOriginal.getImage().getScaledInstance(24, 24, Image.SCALE_SMOOTH);
        btnGuardar = new JButton("Guardar", new ImageIcon(enterScaled));

        ImageIcon enterOriginal2 = new ImageIcon(getClass().getResource("/images/cancelar.png"));
        Image enterScaled2 = enterOriginal2.getImage().getScaledInstance(24, 24, Image.SCALE_SMOOTH);
        btnCancelar = new JButton("Cancelar", new ImageIcon(enterScaled2));
    }

}
