package cr.ac.una.reservas.presentation.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.time.LocalDate;
import java.util.Map;

public class EstadisticasView extends JPanel {
    private JPanel rootPanel;
    private JPanel panelRecursos;
    private JPanel panelActividades;
    private JPanel panelFiltroRecursos;
    private JPanel panelFiltroActividades;
    private JPanel panelCentroRecursos;
    private JPanel panelCentroActividades;
    private JPanel panelPdf;
    private JTextField txtDesdeRecursos;
    private JTextField txtHastaRecursos;
    private JTextField txtDesdeActividades;
    private JTextField txtHastaActividades;
    private DefaultTableModel modeloRecursos;
    private DefaultTableModel modeloActividades;
    private JTable tablaRecursos;
    private JTable tablaActividades;
    private JPanel panelGraficoRecursos;
    private JPanel panelGraficoActividades;
    private JButton btnRecursos;
    private JButton btnActividades;
    private JButton btnPdf;

    public EstadisticasView() {
        $$$setupUI$$$();
        if (rootPanel != this) {
            add(rootPanel);
        }
    }

    private void createUIComponents() {
        modeloRecursos = new DefaultTableModel(new Object[]{"Categoria", "Cantidad"}, 0);
        modeloActividades = new DefaultTableModel(new Object[]{"Semana", "Cantidad"}, 0);
        tablaRecursos = new JTable(modeloRecursos);
        tablaActividades = new JTable(modeloActividades);
    }

    public LocalDate getDesdeRecursos() {
        return LocalDate.parse(txtDesdeRecursos.getText().trim());
    }

    public LocalDate getHastaRecursos() {
        return LocalDate.parse(txtHastaRecursos.getText().trim());
    }

    public LocalDate getDesdeActividades() {
        return LocalDate.parse(txtDesdeActividades.getText().trim());
    }

    public LocalDate getHastaActividades() {
        return LocalDate.parse(txtHastaActividades.getText().trim());
    }

    public void renderizarGraficoBarrasRecursos(Map<String, Integer> datos) {
        llenarTablaYGrafico(modeloRecursos, panelGraficoRecursos, datos, "Recursos");
    }

    public void renderizarGraficoBarrasActividades(Map<String, Integer> datos) {
        llenarTablaYGrafico(modeloActividades, panelGraficoActividades, datos, "Actividades");
    }

    private void llenarTablaYGrafico(DefaultTableModel modelo, JPanel panel, Map<String, Integer> datos, String titulo) {
        modelo.setRowCount(0);
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        if (datos != null) {
            for (Map.Entry<String, Integer> e : datos.entrySet()) {
                modelo.addRow(new Object[]{e.getKey(), e.getValue()});
                dataset.addValue(e.getValue(), titulo, e.getKey());
            }
        }
        JFreeChart chart = ChartFactory.createBarChart(titulo, "", "Cantidad", dataset);
        panel.removeAll();
        panel.add(new ChartPanel(chart), BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }

    public DefaultTableModel getModeloRecursos() {
        return modeloRecursos;
    }

    public DefaultTableModel getModeloActividades() {
        return modeloActividades;
    }

    public JButton getBtnRecursos() {
        return btnRecursos;
    }

    public JButton getBtnActividades() {
        return btnActividades;
    }

    public JButton getBtnPdf() {
        return btnPdf;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(1, 2, new Insets(8, 8, 8, 8), -1, -1, true, false));
        panelRecursos = new JPanel();
        panelRecursos.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        rootPanel.add(panelRecursos, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        panelFiltroRecursos = new JPanel();
        panelFiltroRecursos.setLayout(new GridLayoutManager(1, 6, new Insets(0, 0, 0, 0), -1, -1));
        panelRecursos.add(panelFiltroRecursos, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Recursos reservados");
        panelFiltroRecursos.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Desde:");
        panelFiltroRecursos.add(label2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtDesdeRecursos = new JTextField();
        panelFiltroRecursos.add(txtDesdeRecursos, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Hasta:");
        panelFiltroRecursos.add(label3, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtHastaRecursos = new JTextField();
        panelFiltroRecursos.add(txtHastaRecursos, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnRecursos = new JButton();
        btnRecursos.setText("Calcular recursos");
        panelFiltroRecursos.add(btnRecursos, new GridConstraints(0, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panelCentroRecursos = new JPanel();
        panelCentroRecursos.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelRecursos.add(panelCentroRecursos, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panelCentroRecursos.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPane1.setViewportView(tablaRecursos);
        panelGraficoRecursos = new JPanel();
        panelGraficoRecursos.setLayout(new BorderLayout(0, 0));
        panelCentroRecursos.add(panelGraficoRecursos, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        panelActividades = new JPanel();
        panelActividades.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        rootPanel.add(panelActividades, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        panelFiltroActividades = new JPanel();
        panelFiltroActividades.setLayout(new GridLayoutManager(1, 6, new Insets(0, 0, 0, 0), -1, -1));
        panelActividades.add(panelFiltroActividades, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Actividades calendarizadas");
        panelFiltroActividades.add(label4, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("Desde:");
        panelFiltroActividades.add(label5, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtDesdeActividades = new JTextField();
        panelFiltroActividades.add(txtDesdeActividades, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label6 = new JLabel();
        label6.setText("Hasta:");
        panelFiltroActividades.add(label6, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtHastaActividades = new JTextField();
        panelFiltroActividades.add(txtHastaActividades, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnActividades = new JButton();
        btnActividades.setText("Calcular actividades");
        panelFiltroActividades.add(btnActividades, new GridConstraints(0, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panelCentroActividades = new JPanel();
        panelCentroActividades.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelActividades.add(panelCentroActividades, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JScrollPane scrollPane2 = new JScrollPane();
        panelCentroActividades.add(scrollPane2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPane2.setViewportView(tablaActividades);
        panelGraficoActividades = new JPanel();
        panelGraficoActividades.setLayout(new BorderLayout(0, 0));
        panelCentroActividades.add(panelGraficoActividades, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        panelPdf = new JPanel();
        panelPdf.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelActividades.add(panelPdf, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnPdf = new JButton();
        btnPdf.setText("PDF");
        panelPdf.add(btnPdf, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
