package cr.ac.una.reservas.presentation.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;


public class LoginView extends JFrame {
    private JPanel contentPane;
    private JLabel lblId;
    private JLabel lblClave;
    private JTextField txtId;
    private JPasswordField txtClave;
    private JButton btnIngresar;
    private JPanel loginPanel;
    private JLabel lbLogo;
    private JButton btnCancelar;
    private JButton btnCambiarClave;

    public LoginView() {
        $$$setupUI$$$();
        setContentPane(contentPane);
        setTitle("Ingreso al sistema");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(360, 280);
        setLocationRelativeTo(null);
    }

    public String getTxtId() {
        return txtId.getText().trim();
    }

    public String getTxtClave() {
        return new String(txtClave.getPassword());
    }

    public JButton getBtnIngresar() {
        return btnIngresar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnCambiarClave() {
        return btnCambiarClave;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(1, 1, new Insets(15, 15, 15, 15), -1, -1));
        loginPanel = new JPanel();
        loginPanel.setLayout(new GridLayoutManager(4, 4, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(loginPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(300, 220), null, 0, false));
        btnIngresar.setText("Ingresar");
        loginPanel.add(btnIngresar, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(109, 34), null, 0, false));
        lbLogo.setText("");
        loginPanel.add(lbLogo, new GridConstraints(0, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(55, 55), null, 0, false));
        txtId = new JTextField();
        loginPanel.add(txtId, new GridConstraints(1, 1, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(109, 34), null, 0, false));
        lblId = new JLabel();
        lblId.setText("ID");
        loginPanel.add(lblId, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(50, 27), null, 0, false));
        lblClave = new JLabel();
        lblClave.setText("Clave:");
        loginPanel.add(lblClave, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(50, 17), null, 0, false));
        txtClave = new JPasswordField();
        txtClave.setText("");
        loginPanel.add(txtClave, new GridConstraints(2, 1, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(109, 34), null, 0, false));
        btnCancelar.setText("Cancelar");
        loginPanel.add(btnCancelar, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(109, 34), null, 0, false));
        btnCambiarClave.setText("Cambiar");
        loginPanel.add(btnCambiarClave, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(109, 34), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    private void createUIComponents() {
        ImageIcon original = new ImageIcon(getClass().getResource("/images/login.png"));
        Image scaledImage = original.getImage().getScaledInstance(55, 55, Image.SCALE_SMOOTH);
        lbLogo = new JLabel(new ImageIcon(scaledImage));

        ImageIcon enterOriginal = new ImageIcon(getClass().getResource("/images/login-enter.png"));
        Image enterScaled = enterOriginal.getImage().getScaledInstance(24, 24, Image.SCALE_SMOOTH);
        btnIngresar = new JButton("Ingresar", new ImageIcon(enterScaled));

        ImageIcon enterOriginal2 = new ImageIcon(getClass().getResource("/images/cancelar.png"));
        Image enterScaled2 = enterOriginal2.getImage().getScaledInstance(24, 24, Image.SCALE_SMOOTH);
        btnCancelar = new JButton("Cancelar", new ImageIcon(enterScaled2));

        ImageIcon enterOriginal3 = new ImageIcon(getClass().getResource("/images/cambiar-imagen.png"));
        Image enterScaled3 = enterOriginal3.getImage().getScaledInstance(24, 24, Image.SCALE_SMOOTH);
        btnCambiarClave = new JButton("Cambiar", new ImageIcon(enterScaled3));
    }

}
