package cr.ac.una.reservas.presentation.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import cr.ac.una.reservas.logic.Rol;
import cr.ac.una.reservas.logic.Usuario;

import javax.swing.*;
import java.awt.*;

public class MainFrame extends JFrame {
    private JPanel contentPane;
    private JTabbedPane tabs;
    private Usuario usuarioAutenticado;
    private JMenuItem itemCambiarClave;

    private ReservasView reservasView;
    private FuncionariosView funcionariosView;
    private CategoriasView categoriasView;
    private RecursosView recursosView;
    private CalendarizacionView calendarizacionView;
    private ActividadesView actividadesView;
    private EstadisticasView estadisticasView;

    public MainFrame(Usuario usuarioAutenticado) {
        this.usuarioAutenticado = usuarioAutenticado;
        setTitle("Sistema de Reserva de Recursos - " + usuarioAutenticado.getId());
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(1100, 700);
        setLocationRelativeTo(null);
        inicializarComponentes();
        mostrarTabsSegunRol(usuarioAutenticado.getRol());
    }

    public void inicializarComponentes() {
        $$$setupUI$$$();
        setContentPane(contentPane);

        JMenuBar bar = new JMenuBar();
        JMenu menu = new JMenu("Cuenta");
        itemCambiarClave = new JMenuItem("Cambiar clave");
        menu.add(itemCambiarClave);
        bar.add(menu);
        setJMenuBar(bar);

        reservasView = new ReservasView();
        funcionariosView = new FuncionariosView();
        categoriasView = new CategoriasView();
        recursosView = new RecursosView();
        calendarizacionView = new CalendarizacionView();
        actividadesView = new ActividadesView();
        estadisticasView = new EstadisticasView();
    }

    public void mostrarTabsSegunRol(Rol rol) {
        tabs.removeAll();
        if (rol == Rol.FUNCIONARIO) {
            tabs.addTab("Reservas", reservasView);
        }
        if (rol == Rol.ADMINISTRADOR) {
            ImageIcon iconFuncionarios = new ImageIcon(getClass().getResource("/images/funcionario.png"));
            Image imagenFuncionarios = iconFuncionarios.getImage().getScaledInstance(16, 16, Image.SCALE_SMOOTH);
            tabs.addTab("Funcionarios", new ImageIcon(imagenFuncionarios), funcionariosView);
            tabs.addTab("Categorias", categoriasView);
            tabs.addTab("Recursos", recursosView);
        }
        tabs.addTab("Calendarizacion", calendarizacionView);
        tabs.addTab("Actividades", actividadesView);
        tabs.addTab("Estadisticas", estadisticasView);
    }

    public Usuario getUsuarioAutenticado() {
        return usuarioAutenticado;
    }

    public JMenuItem getItemCambiarClave() {
        return itemCambiarClave;
    }

    public ReservasView getReservasView() {
        return reservasView;
    }

    public FuncionariosView getFuncionariosView() {
        return funcionariosView;
    }

    public CategoriasView getCategoriasView() {
        return categoriasView;
    }

    public RecursosView getRecursosView() {
        return recursosView;
    }

    public CalendarizacionView getCalendarizacionView() {
        return calendarizacionView;
    }

    public ActividadesView getActividadesView() {
        return actividadesView;
    }

    public EstadisticasView getEstadisticasView() {
        return estadisticasView;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabs = new JTabbedPane();
        contentPane.add(tabs, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
