package cr.ac.una.reservas.presentation.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import cr.ac.una.reservas.logic.Categoria;
import cr.ac.una.reservas.logic.Reserva;
import cr.ac.una.reservas.logic.ReservaDTO;
import cr.ac.una.reservas.logic.ServiceModel;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

public class ReservasView extends JPanel {
    private JPanel rootPanel;
    private JPanel panelNorte;
    private JPanel panelIA;
    private JPanel panelForm;
    private JPanel panelBotones;
    private JLabel lblFrase;
    private JTextArea txtFrase;
    private JTextField txtActividad;
    private JTextField txtFecha;
    private JTextField txtHoraInicio;
    private JTextField txtHoraFin;
    private JPanel panelCategorias;
    private List<JCheckBox> checksCategorias = new ArrayList<>();
    private JTable tabla;
    private DefaultTableModel modelo;
    private JButton btnUsarIA;
    private JButton btnAplicar;
    private JButton btnCancelar;
    private JButton btnPdf;

    public ReservasView() {
        $$$setupUI$$$();
        if (rootPanel != this) {
            add(rootPanel);
        }
        cargarChecksCategorias();
    }

    private void createUIComponents() {
        modelo = new DefaultTableModel(new Object[]{"Id", "Actividad", "Fecha", "Inicio", "Fin", "Estado"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabla = new JTable(modelo);
    }

    public void cargarChecksCategorias() {
        panelCategorias.removeAll();
        checksCategorias.clear();
        for (Categoria c : ServiceModel.getInstance().buscarCategorias("")) {
            JCheckBox cb = new JCheckBox(c.getDescripcion());
            cb.putClientProperty("catId", c.getId());
            checksCategorias.add(cb);
            panelCategorias.add(cb);
        }
        panelCategorias.revalidate();
        panelCategorias.repaint();
    }

    public String getTxtFrase() {
        return txtFrase.getText();
    }

    public String getTxtActividad() {
        return txtActividad.getText().trim();
    }

    public String getTxtFecha() {
        return txtFecha.getText().trim();
    }

    public String getTxtHoraInicio() {
        return txtHoraInicio.getText().trim();
    }

    public String getTxtHoraFin() {
        return txtHoraFin.getText().trim();
    }

    public List<String> getCategoriasSeleccionadas() {
        List<String> ids = new ArrayList<>();
        for (JCheckBox cb : checksCategorias) {
            if (cb.isSelected()) {
                ids.add((String) cb.getClientProperty("catId"));
            }
        }
        return ids;
    }

    public void LlenarFormularioConDTO(ReservaDTO dto) {
        if (dto.getActividad() != null) {
            txtActividad.setText(dto.getActividad());
        }
        if (dto.getFecha() != null) {
            txtFecha.setText(dto.getFecha().toString());
        }
        if (dto.getHoraInicio() != null) {
            txtHoraInicio.setText(dto.getHoraInicio().toString());
        }
        if (dto.getHoraFin() != null) {
            txtHoraFin.setText(dto.getHoraFin().toString());
        }
        for (JCheckBox cb : checksCategorias) {
            String id = (String) cb.getClientProperty("catId");
            cb.setSelected(dto.getCategoriasExtraidas() != null && dto.getCategoriasExtraidas().contains(id));
        }
    }

    public void actualizarTablaMisReservas(List<Reserva> reservas) {
        modelo.setRowCount(0);
        DateTimeFormatter tf = DateTimeFormatter.ofPattern("HH:mm");
        for (Reserva r : reservas) {
            modelo.addRow(new Object[]{
                    r.getId(),
                    r.getActividad(),
                    r.getFecha(),
                    r.getHoraInicio() == null ? "" : r.getHoraInicio().format(tf),
                    r.getHoraFin() == null ? "" : r.getHoraFin().format(tf),
                    r.getEstado()
            });
        }
    }

    public JTable getTabla() {
        return tabla;
    }

    public DefaultTableModel getModelo() {
        return modelo;
    }

    public JButton getBtnUsarIA() {
        return btnUsarIA;
    }

    public JButton getBtnAplicar() {
        return btnAplicar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnPdf() {
        return btnPdf;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(3, 1, new Insets(8, 8, 8, 8), -1, -1));
        panelNorte = new JPanel();
        panelNorte.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        rootPanel.add(panelNorte, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panelIA = new JPanel();
        panelIA.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        panelNorte.add(panelIA, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblFrase = new JLabel();
        lblFrase.setText("Frase (IA):");
        panelIA.add(lblFrase, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panelIA.add(scrollPane1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(-1, 60), null, 0, false));
        txtFrase = new JTextArea();
        txtFrase.setLineWrap(true);
        txtFrase.setRows(3);
        scrollPane1.setViewportView(txtFrase);
        btnUsarIA = new JButton();
        btnUsarIA.setText("Usar IA");
        panelIA.add(btnUsarIA, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panelForm = new JPanel();
        panelForm.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        panelNorte.add(panelForm, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Actividad:");
        panelForm.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtActividad = new JTextField();
        panelForm.add(txtActividad, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Fecha (yyyy-MM-dd):");
        panelForm.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtFecha = new JTextField();
        panelForm.add(txtFecha, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Hora inicio (HH:mm):");
        panelForm.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtHoraInicio = new JTextField();
        panelForm.add(txtHoraInicio, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Hora fin (HH:mm):");
        panelForm.add(label4, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtHoraFin = new JTextField();
        panelForm.add(txtHoraFin, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane2 = new JScrollPane();
        panelNorte.add(scrollPane2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(-1, 80), null, 0, false));
        panelCategorias = new JPanel();
        panelCategorias.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        scrollPane2.setViewportView(panelCategorias);
        final JScrollPane scrollPane3 = new JScrollPane();
        rootPanel.add(scrollPane3, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPane3.setViewportView(tabla);
        panelBotones = new JPanel();
        panelBotones.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        rootPanel.add(panelBotones, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnAplicar = new JButton();
        btnAplicar.setText("Aplicar reserva");
        panelBotones.add(btnAplicar, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnCancelar = new JButton();
        btnCancelar.setText("Cancelar reserva");
        panelBotones.add(btnCancelar, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnPdf = new JButton();
        btnPdf.setText("PDF");
        panelBotones.add(btnPdf, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
